title: Technical Reference
description: machine learning, creative technology, programming reference
theme: just-the-docs

url: https://mozartfish.github.io/tech-reference

aux_links:
  Template Repository: https://github.com/mozartfish/technical-reference