title: Technical Reference
description: machine learning, creative technology, programming reference
theme: just-the-docs

url: https://mozartfish.github.io/technical-reference

aux_links:
  GitHub: https://github.com/mozartfish/technical-reference

color_scheme: styles